export const ADD_TASK="ADD_TASK"
export const DELETE_TASK="DELETE_TASK"
export const ISDONE_TASK="ISDONE_TASK"
export const ISNOTDONE_TASK="ISNOTDONE_TASK"
export const COMPLETE_TASK="COMPLETE_TASK"
export const EDIT_TASK="EDIT_TASK"

